"""Type stubs for pyTARA (TARA Python API)

Provides type hints and method signatures for the pyTARA API library.
Enables IDE autocomplete and parameter hints when working with pyTARA scripts.

Usage:
    import pyPowerGEM.pyTARA as pt
    api = pt.taraAPI(logFilePath="tara_log.txt")
    api.loadPowerFlowCase(caseFilePath=r'case.raw', version=33)
"""

class taraAPI:
    """Main TARA API class for programmatic access to TARA power system calculations"""

    def __init__(self, logFilePath: str | None = None) -> None: ...

    # ============ TARA Setup ============
    def printPathToDLL(self) -> object: ...
    def fileInfo(self, *, path: str | None = None, version: object | None = None) -> object: ...
    def getAdditionalTaraOptionsFromTARA(self) -> object: ...
    def setAdditionalTaraOptionsFromAPI(self, *, addTaraOpsObj: bool | None = None) -> object: ...
    def setMaxDimensions(self, *, taraDimsObj: object | None = None) -> object: ...
    def openTaraLogFile(self, *, logFilePath: str | None = None) -> object: ...
    def getMaxDimensions(self) -> object: ...
    def getTaraWarnMessage(self, *, iWarn: int | None = None) -> object: ...
    def loopWarningMessages(self, *, warnCategory: object | None = None) -> object: ...
    def loopInputFileWarnings(self) -> object: ...
    def numWarnMessages(self) -> object: ...

    # ============ Case Management ============
    def loadRawCase(self, *, caseFilePath: str | None = None, rawVer: object | None = None) -> object: ...
    def saveRawCase(self, *, caseFilePath: str | None = None, rawVerOut: object | None = None) -> object: ...
    def loadEpcCase(self, *, caseFilePath: str | None = None, epcVer: object | None = None) -> object: ...
    def saveEpcCase(self, *, caseFilePath: str | None = None, epcVerOut: object | None = None) -> object: ...
    def loadPowerFlowCase(self, *, caseFilePath: str | None = None, version: object | None = None) -> object: ...
    def solveCase(self) -> object: ...
    def updateCase(self, *, equipObj: object | None = None, outFile: str | None = None) -> object: ...
    def applyInchFile(self, *, inchFilePath: int | None = None) -> object: ...
    def getACLFBaseOptions(self) -> object: ...
    def setACLFBaseOptions(self, *, aclfOptsObj: object | None = None) -> object: ...

    # ============ Read-Only Devices ============
    def getOwner(self, *, iOwner: int | None = None) -> object: ...
    def getSwingBus(self) -> object: ...
    def numStations(self) -> object: ...
    def numSwitches(self) -> object: ...

    # ============ Nodes ============
    def loopNodes(self) -> object: ...
    def numNodes(self) -> object: ...
    def getPrimaryBusIBus(self, *, iNode: int | None = None, iBus: int | None = None, removeProperties: bool | None = None) -> object: ...

    # ============ VSC Devices ============
    def getVsc(self, *, iVsc: int | None = None) -> object: ...
    def loopVscs(self) -> object: ...
    def numVSCs(self) -> object: ...

    # ============ EMS Devices ============
    def getEmsNode(self, *, iNode: int | None = None, iBus: int | None = None, busNum: int | None = None, removeProperties: bool | None = None, addPrimaryBus: bool | None = None) -> object: ...
    def getEmsStation(self, *, iStation: int | None = None, removeProperties: bool | None = None) -> object: ...
    def getEmsSwitch(self, *, iBran: int | None = None, iSwitch: int | None = None, removeProperties: bool | None = None) -> object: ...

    # ============ FACTS Devices ============
    def getFact(self, *, iFact: int | None = None) -> object: ...
    def loopFacts(self) -> object: ...
    def numFacts(self) -> object: ...

    # ============ Query and Filter ============
    def isInArea(self, *, obj: object | None = None, areas: object | None = None) -> object: ...
    def filterForArea(self, *, objList: object | None = None, areas: object | None = None) -> object: ...
    def calcAreaZoneTotals(self, *, areaZoneMode: int | None = None) -> object: ...

    # ============ Area ============
    def getArea(self, *, areaNum: int | None = None, iArea: int | None = None, removeProperties: bool | None = None) -> object: ...
    def deleteArea(self, *, number: object | None = None, areaName: str | None = None, ties: bool | None = None, outFile: str | None = None) -> object: ...
    def loopAreas(self, *, removeProperties: bool | None = None) -> object: ...
    def numAreas(self) -> object: ...

    # ============ Bus ============
    def getBus(self, *, busNum: int | None = None, busName: str | None = None, kv: float | str | None = None, iBus: int | None = None, debug: bool | None = None) -> object: ...
    def addBus(self, *, busObj: object | None = None, outFile: str | None = None) -> object: ...
    def deleteBus(self, *, busObj: object | None = None, iBus: int | None = None, busNum: int | None = None, outFile: str | None = None) -> object: ...
    def changeBusNum(self, *, busObj: object | None = None, newBusNum: int | None = None, iBus: int | None = None, outFile: str | None = None) -> object: ...
    def getBusEquipment(self, *, busObj: object | None = None, iBus: int | None = None) -> object: ...
    def isBusPrimary(self, *, iBus: int | None = None) -> object: ...
    def mergeBuses(self, *, removeBusNum: int | None = None, mergeBusNum: int | None = None, mergeBusObj: object | None = None, removeBusObj: bool | None = None, mergeiBus: object | None = None, removeiBus: bool | None = None, outFile: str | None = None) -> object: ...
    def splitBus(self, *, splitBusNum: int | None = None, splitBusName: str | None = None, iBus: int | None = None, busNum: int | None = None, busObj: object | None = None, outFile: str | None = None) -> object: ...
    def isStarBus(self, *, iBus: int | None = None, busNum: int | None = None) -> object: ...
    def loopBuses(self, *, allNodes: object | None = None) -> object: ...
    def numBuses(self) -> object: ...
    def getAllBusDistances(self, *, sourceBusNum: int | None = None, openPars: bool | None = None, includeOpened: int | None = None, maxLevels: int | None = None) -> object: ...
    def getBusDistance(self, *, sourceBusNum: int | None = None, targetBusNum: int | None = None, openPars: bool | None = None, includeOpened: int | None = None, maxLevels: int | None = None) -> object: ...
    def getNextAvailBusNum(self, *, maxBus: object | None = None, minBus: object | None = None) -> object: ...

    # ============ Generator ============
    def getGenerator(self, *, busNum: int | None = None, genId: str | None = None, iGen: int | None = None) -> object: ...
    def addGenerator(self, *, genObj: object | None = None, outFile: str | None = None) -> object: ...
    def deleteGenerator(self, *, genObj: object | None = None, iGen: int | None = None, outFile: str | None = None) -> object: ...
    def moveGenerator(self, *, genObj: object | None = None, iGen: int | None = None, busNum: int | None = None, targetBusNum: int | None = None, genId: str | None = None, NewID: str | None = None, outFile: str | None = None) -> object: ...
    def loopGenerators(self) -> object: ...
    def numGenerators(self) -> object: ...
    def scaleGeneration(self, *, area: object | None = None, subsystemName: str | None = None, scaleMethod: object | None = None, valueOption: object | None = None, machineLimit: object | None = None, value: object | None = None, outFile: str | None = None) -> object: ...

    # ============ Transmission Line ============
    def getLine(self, *, frBus: object | None = None, toBus: object | None = None, cktId: str | None = None, iBran: int | None = None, sectNum: int | None = None, addFlows: bool | None = None, addOwner: bool | None = None, getAnyBranch: object | None = None) -> object: ...
    def addLine(self, *, lineObj: object | None = None, outFile: str | None = None) -> object: ...
    def deleteLine(self, *, lineObj: object | None = None, iBran: int | None = None, frBus: object | None = None, toBus: object | None = None, cktId: str | None = None, outFile: str | None = None) -> object: ...
    def moveLine(self, *, lineObj: object | None = None, frBus: object | None = None, toBus: object | None = None, cktId: str | None = None, iBran: int | None = None, TargetBusNumTo: object | None = None, TargetBusNumFr: object | None = None, newCkt: object | None = None, outFile: str | None = None) -> object: ...
    def tapLine(self, *, frBus: object | None = None, toBus: object | None = None, cktId: str | None = None, lineObj: object | None = None, iBran: int | None = None, percentTap: object | None = None, orientation: object | None = None, newBusNum: int | None = None, newBusName: str | None = None, outFile: str | None = None) -> object: ...
    def loopLines(self) -> object: ...
    def loopBranches(self) -> object: ...
    def numBranches(self) -> object: ...
    def isMultiSectionLine(self, *, lineObj: object | None = None, iBran: int | None = None) -> object: ...
    def loopDCLines(self) -> object: ...
    def getDCLine(self, *, iDC: int | None = None) -> object: ...
    def numTwoTermDCLines(self) -> object: ...

    # ============ Load ============
    def getLoad(self, *, busNum: int | None = None, loadId: str | None = None, iLoad: int | None = None) -> object: ...
    def addLoad(self, *, loadObj: object | None = None, outFile: str | None = None) -> object: ...
    def deleteLoad(self, *, loadObj: object | None = None, iLoad: int | None = None, busNum: int | None = None, loadId: str | None = None, outFile: str | None = None) -> object: ...
    def moveLoad(self, *, loadObj: object | None = None, iLoad: int | None = None, busNum: int | None = None, targetBusNum: int | None = None, loadId: str | None = None, NewID: str | None = None, MW: float | str | None = None, percent: object | None = None, outFile: str | None = None) -> object: ...
    def scaleLoad(self, *, area: object | None = None, subsystemName: str | None = None, scaleMethod: object | None = None, valueOption: object | None = None, pValue: object | None = None, nonconform: object | None = None, outFile: str | None = None) -> object: ...
    def loopLoads(self) -> object: ...
    def numLoads(self) -> object: ...

    # ============ Shunts ============
    def addShunt(self, *, shuntObj: object | None = None, outFile: str | None = None) -> object: ...
    def getBusShunt(self, *, busNum: int | None = None, shuntId: str | None = None, iBus: int | None = None, iShunt: int | None = None) -> object: ...
    def deleteBusShunt(self, *, busShuntObj: object | None = None, iShunt: int | None = None, outFile: str | None = None) -> object: ...
    def moveBusShunt(self, *, fxShuntObj: object | None = None, busNum: int | None = None, newId: str | None = None, iShunt: int | None = None, targetBusNum: int | None = None, shuntId: str | None = None, outFile: str | None = None) -> object: ...
    def getSwitchedShunt(self, *, busNum: int | None = None, iBus: int | None = None, iShunt: int | None = None) -> object: ...
    def deleteSwitchedShunt(self, *, swShuntObj: object | None = None, iShunt: int | None = None, outFile: str | None = None) -> object: ...
    def moveSwitchedShunt(self, *, swShuntObj: object | None = None, busNum: int | None = None, newId: str | None = None, iShunt: int | None = None, targetBusNum: int | None = None, shuntId: str | None = None, outFile: str | None = None) -> object: ...
    def isSwitchedShunt(self, *, iShunt: int | None = None) -> object: ...
    def loopShunts(self) -> object: ...
    def loopBusShunts(self) -> object: ...
    def loopSwitchedShunts(self) -> object: ...
    def numShunts(self) -> object: ...

    # ============ Subsystem ============
    def getSubsystem(self, *, iSubsys: int | None = None, subsystemName: str | None = None) -> object: ...
    def addSubsystem(self, *, subsystemObj: object | None = None) -> object: ...
    def deleteSubsystem(self, *, iSubSys: int | None = None, subsystemName: str | None = None, ties: bool | None = None, outFile: str | None = None) -> object: ...
    def loopSubsystems(self) -> object: ...
    def numSubsystems(self) -> object: ...

    # ============ Transformer ============
    def getTransformer(self, *, W1BusNum: int | None = None, W2BusNum: int | None = None, W3BusNum: int | None = None, cktId: str | None = None, frBus: object | None = None, toBus: object | None = None, iTran: int | None = None, iBran: int | None = None) -> object: ...
    def addTransformer(self, *, transObj: object | None = None, outFile: str | None = None) -> object: ...
    def deleteTransformer(self, *, transObj: object | None = None, iTrans: int | None = None, outFile: str | None = None) -> object: ...
    def moveTransformer(self, *, tranObj: object | None = None, frBus: object | None = None, toBus: object | None = None, cktId: str | None = None, iTran: int | None = None, newCkt: object | None = None, TargetW1BusNum: int | None = None, TargetW2BusNum: int | None = None, TargetW3BusNum: int | None = None, outFile: str | None = None) -> object: ...
    def loopTransformers(self, *, twoWind: object | None = None, threeWind: object | None = None, par: object | None = None) -> object: ...
    def loop2WindTransformers(self) -> object: ...
    def loop3WindTransformers(self) -> object: ...
    def loopPars(self) -> object: ...
    def numTransformers(self) -> object: ...

    # ============ Zone ============
    def getZone(self, *, iZone: int | None = None, removeProperties: bool | None = None) -> object: ...
    def deleteZone(self, *, number: object | None = None, zoneName: str | None = None, ties: bool | None = None, outFile: str | None = None) -> object: ...
    def loopZones(self, *, removeProperties: bool | None = None) -> object: ...

    # ============ Properties ============
    @property
    def isACSolutionConverged(self) -> bool | None: ...

    @property
    def iterations(self) -> int: ...
